import matplotlib.animation as animation


class Simulation:
    """
    Simulation scene for simulating movements of robots with controllers
    """
    def __init__(self, fig, ax, robots, controller):
        # for drawing single simulation scene
        self.fig = fig
        self.ax = ax

        self.robots = robots
        self.controller = controller

        # for storing animation object and then refresh
        self.ani = None

    def initialize_scene(self):
        """
        initialize the simulation scene
        :return: list of artists for animation, [[robot1_visible_region1, robot1_visible_region2, ...],
        [robot1_point, ...]]
        """
        self.ax.set_xlim(-10, 10)
        self.ax.set_ylim(-10, 10)
        self.ax.set_aspect('equal')

        # plot desired trace
        self.ax.add_patch(self.controller.desired_trace_artist)

        # plot initial scene of robots and their visible region
        for robot in self.robots:
            for region in robot.visible_region_artist:
                self.ax.add_patch(region)
            self.ax.add_patch(robot.robot_point_artist)

        return [region for robot in self.robots for region in robot.visible_region_artist] + \
            [robot.robot_point_artist for robot in self.robots]

    def update_scene(self, data):
        """
        update the simulation scene with controller output
        :param data: speeds of robots generated by controller's speed_gen generator
        :return: list of updated artists for animation, [[robot1_visible_region1, robot1_visible_region2, ...],
        [robot1_point, ...]]
        """
        # update robot position with controller output
        dt, speeds = data
        for robot, speed in zip(self.robots, speeds):
            robot.update(dt, speed)

        return [region for robot in self.robots for region in robot.visible_region_artist] + \
            [robot.robot_point_artist for robot in self.robots]

    def show_animation(self):
        """
        show the animation of simulation scene with FuncAnimation of matplotlib
        """
        self.ani = animation.FuncAnimation(self.fig, self.update_scene, self.controller.speed_gen,
                                           init_func=self.initialize_scene, interval=100, blit=True,
                                           cache_frame_data=False, save_count=100)

    def save_animation(self, filename, fps=60):
        self.ani.save(filename, fps=fps, dpi=200)
